sudo: required

language: nix

script:
  - nix-build ./nix/screenshot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: result
  on:
    branch:
      - master

notifications:
  email:
    on_success: never
