language: nix

script:
  - nix-build ./scripts/screenshot.nix
  - ./scripts/images.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: screenshots
  local-dir: dist
  on:
    branch:
      - master

notifications:
  email:
    on_success: never